name: Vimalraj
description: >
    A simple jekyll theme aimed at programmers who like clean interface to write posts
    and show off some code.
about: >
    Hi! I am vimalraj interested in Open-Source and writing Quality code stuff.Regards Vimal :) !! 

master_repo: false
url: "http://vimalraj571.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Vimal
  avatar:         "https://avatars0.githubusercontent.com/u/8166149?s=250&v=4"
  email:          "vimalraj.ktm95@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: vimalrajktm
  github: https://github.com/vimalraj571
  stackexchange: 
  linkedin: https://www.linkedin.com/in/vimalrajktm/
  # For Google Authorship https://plus.google.com/authorship
  google_plus: 

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
